// <auto-generated />
using System;
using Casino_Royale_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Casino_Royale_Api.Migrations
{
    [DbContext(typeof(CasinoDbContext))]
    partial class CasinoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Casino_Royale_Api.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    
                    b.Property<bool?>("active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<double?>("currentMoney")
                        .HasColumnName("currentMoney")
                        .HasColumnType("float");

                    b.Property<double?>("totalEarned")
                        .HasColumnName("totalEarned")
                        .HasColumnType("float");

                    b.Property<double?>("totalLost")
                        .HasColumnName("totalLost")
                        .HasColumnType("float");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
